function Test-ProgisticsAPI {
    $Proxy = New-WebServiceProxy -Uri http://dlt-progis01/amp/wsdl -Class Progistics
    $Proxy | gm | where name -eq ListCountries | fL
    $Proxy.ListCountries()
    $proxy.BeginListCountries()
    $Request = New-Object Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1http___dlt_progis01_amp_wsdl.ListCountriesRequest
    $Request.preProcess = "core"
    $Request.postProcess = "core"

    $Proxy.ListCountries($Request)

    $Proxy | gm | where name -eq ListUnits | fL
    $Request = New-Object Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1http___dlt_progis01_amp_wsdl.ListUnitsRequest
    $Request.preProcess = "core"
    $Request.postProcess = "core"
    $Proxy.ListUnits($Request)

    get-service -ComputerName dlt-progis01 | where displayname -Match progis
    get-service -ComputerName dlt-progis01 -Name AMPService | Restart-Service
}